### ISSUE TITLE
Create get by application id

### ISSUE THREAD

**Issue by Niccko** [IVBO-07-19/scholarship-culture-part#6]
"_title" учитывать не нужно. Он служит для пояснения что к чему относится.
![image](https://user-images.githubusercontent.com/61467290/119666832-6532a600-be3e-11eb-9956-77fa775c8be4.png)
![image](https://user-images.githubusercontent.com/61467290/119666931-7d0a2a00-be3e-11eb-8d1b-3b96cfaee193.png)

**Comment by MihKon** [comment]
we did it
